---
title: "Analytics"
author: "Dante Ruiz"
date: "7/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(leaflet)
library(kableExtra)
```

```{r}
tbl_restaurants <- 
  read_csv("../data/output/restaurants.csv",
           col_types = cols(
                categories = col_character(),
                cluster = col_double(),
                business_id = col_character(),
                metropolitan_area = col_character(),
                name = col_character(),
                latitude = col_double(),
                longitude = col_double(),
                review_count = col_double(),
                stars = col_double(),
                year = col_double(),
                num_checkins = col_double(),
                year_1 = col_double(),
                num_tips = col_double(),
                year_2 = col_double(),
                num_reviews = col_double(),
                mean_stars_reviews = col_double(),
                is_restrautrant = col_logical()
                )
           )
```


```{r}
tbl_restaurants %>% 
  ggplot( aes(review_count, stars) ) + 
  geom_jitter(alpha = 0.2) + 
  labs(title = "Review count vs Stars") +
  facet_wrap(~metropolitan_area)  + 
  labs(title = "Review count vs Stars")
```




```{r}
tbl_restaurants %>% 
  ggplot( aes(num_checkins, stars) ) + 
  geom_jitter(alpha = 0.2) + 
  labs(title = "Check ins vs Stars") +
  facet_wrap(~metropolitan_area)  + 
  labs(title = "Check ins vs Stars")
```


```{r}
# Calculate the top 10 restaurants by city
tbl_most_reviewed <-
  tbl_restaurants %>% 
  group_by(metropolitan_area) %>% 
  slice_max(review_count, n = 10)
```


```{r}
fun_graph_map <- function(metro_area = 'Denver, Colorado'){
  # Calculate centers
  map_center <- 
    tbl_most_reviewed %>% 
    group_by(metropolitan_area) %>% 
    summarise(mean_lon = mean(longitude), mean_lat = mean(latitude)) %>% 
    filter(metropolitan_area == metro_area)
  
  # FIlter restaurants
  tbl_poi <-
    tbl_most_reviewed %>% 
    filter(metropolitan_area == metro_area)
  
  # Draw map
  leaflet() %>% 
    addTiles() %>% 
    setView(lng = map_center[[2]]	, lat = map_center[[3]]	, zoom = 11) %>% 
    addMarkers(data  = tbl_poi, 
               popup = ~paste0(
                 '<b>',name,'</b>', 
                 '</br>',"# of reviews: ", review_count,
                 '</br>',"# of avg. stars: ", stars,
                 '</br>',"# of checkins: ", num_checkins,
                 '</br>',"# of tips: ", num_tips,
                 '</br>', "Type of food: ", categories
                 ))
}  


```

```{r}
fun_draw_table <- function(metro_area = 'Denver, Colorado'){
  tbl_most_reviewed %>%
    filter(metropolitan_area == metro_area) %>% 
    select(name, categories, review_count, stars, num_checkins, num_tips, num_reviews) %>% 
    kbl() %>% 
    kable_styling(bootstrap_options = c("striped", "hover"), full_width = F, fixed_thead = T)
}
```


```{r}
tbl_most_reviewed$metropolitan_area %>% unique()
```

## Denver, Colorado

```{r}
fun_graph_map(metro_area = "Denver, Colorado")
```

```{r}
fun_draw_table(metro_area = 'Denver, Colorado')
```



## Columbus, Ohio

```{r}
fun_graph_map(metro_area = "Columbus, Ohio")
```


```{r}
fun_draw_table(metro_area = 'Columbus, Ohio')
```

## Portland, Oregon & Vancouver, Washington

```{r}
fun_graph_map(metro_area = "Portland, Oregon & Vancouver, Washington")
```

```{r}
fun_draw_table(metro_area = 'Portland, Oregon & Vancouver, Washington')
```

## Cambridge, Masachusetts

```{r}
fun_graph_map(metro_area = "Cambridge, Masachusetts")
```

```{r}
fun_draw_table(metro_area = 'Cambridge, Masachusetts')
```

## Austin, Texas

```{r}
fun_graph_map(metro_area = "Austin, Texas")
```

```{r}
fun_draw_table(metro_area = 'Austin, Texas')
```

## Orlando, Florida

```{r}
fun_graph_map(metro_area = "Orlando, Florida")
```

```{r}
fun_draw_table(metro_area = 'Orlando, Florida')
```

## Atlanta, Georgia

```{r}
fun_graph_map(metro_area = "Atlanta, Georgia" )
```

```{r}
fun_draw_table(metro_area = 'Atlanta, Georgia')
```

## Vancouver, British Columbia

```{r}
fun_graph_map(metro_area = "Vancouver, British Columbia" )
```

```{r}
fun_draw_table(metro_area = 'Vancouver, British Columbia')
```

